version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./media:/app/media
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:password@db:5432/it_job_search
    depends_on:
      - db
    command: >
      sh -c "cd backend &&
             python manage.py migrate &&
             python manage.py seed_jobs &&
             python manage.py seed_blogposts &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=it_job_search
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  postgres_data: 